models:
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
      - "6000:50"
   volumes:
      - ./microservices:/app
   command: bash -c "python manage.py makemigrations microapp; python manage.py migrate; python manage.py loaddata db.json; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/microservices/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
   volumes:
      - ./expLayer:/app
   command: bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/expLayer/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./marketplace:/app
   command: bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/marketplace/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
      - .:/app
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python batch.py"
