# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproduct',
            name='coffeeType',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
